mcp_tools/tests/test_command_executor_async.py
The test `test_git_branch_command` was failing in CI environments (issue #4) because it assumed `git branch --show-current` would always return a branch name. However, in CI environments like GitHub Actions, repositories are often checked out in a detached HEAD state, where this command returns an empty string.
This PR modifies the test to handle both scenarios:
1. **Normal branch state**: Validates that the branch name contains only valid characters
2. **Detached HEAD state**: Falls back to verifying we can get commit information using `git rev-parse HEAD` and validates the commit hash format
- Modified `test_git_branch_command` in `mcp_tools/tests/test_command_executor_async.py`
- Added logic to detect empty branch name (detached HEAD state)
- Added fallback validation using commit hash …
=> Fix test_git_branch_command to handle detached HEAD state

prompt/github_issue_workflow.md
This PR adds comprehensive documentation for AI-assisted GitHub issue resolution workflow. The documentation provides a structured approach for handling issues from analysis to completion.
- **Added `prompt/github_issue_workflow.md`**: Complete workflow guide including:
- Step-by-step issue resolution process (6 phases)
- Git commands reference
- Best practices and quality guidelines
- Structured output format templates
- Error handling procedures
1. **Issue Analysis Phase** - Understanding requirements and scope
2. **Planning Phase** - Implementation planning and branch management
3. **Implementation Phase** - Code changes, testing, and documentation
4. **Quality Assurance Phase** - Code review preparation and commit management
5. **Pull Request Phase** - PR creation and best practices …
=> Add comprehensive GitHub issue resolution workflow documentation

.cursor/rules/generate_github_issue.mdc
This PR adds a comprehensive rule file for generating well-structured GitHub issues based on user requests and codebase analysis.
- **New file**: `.cursor/rules/generate_github_issue.mdc`
- Provides guidance for AI assistants on creating actionable GitHub issues
- Includes clarification questions for unclear requirements
- Defines proper issue structure and best practices
- **Issue Analysis**: Guidelines for understanding requests and examining codebase context
- **Requirement Clarification**: Specific questions to ask when user requirements are vague
- **Issue Structure**: Template for titles, descriptions, and metadata
- **Best Practices**: Guidelines for writing clear, actionable issues
- **Quality Checks**: Validation criteria before finalizing issues
- Ensures consistent, …
=> Add GitHub Issue Generation Rule for Cursor

plugins/knowledge_indexer/tests/README.md, plugins/knowledge_indexer/tests/conftest.py, plugins/knowledge_indexer/tests/fixtures/sample_documents/test_document.md, plugins/knowledge_indexer/tests/test_integration.py
Resolves #25 - Currently, the `knowledge_indexer` plugin tests rely heavily on mocks for `ChromaVectorStore`, which means we're not testing actual database interactions. This PR adds comprehensive integration tests that use real ChromaDB instances to catch real-world database issues.
Added a complete suite of **integration tests** that use real ChromaDB instances with proper isolation:
1. **Real Database Operations**
- Actual ChromaDB instance creation and management
- Real embedding generation and storage
- Persistent storage testing
- Collection lifecycle management
2. **Test Isolation & Cleanup**
- Unique temporary directories per test (using UUIDs)
- Unique collection names to prevent interference
- Automatic cleanup after test completion
- No cross-test pollution
3. **Comprehensive …
=> Add ChromaDB integration tests for knowledge_indexer plugin

server/tests/test_mcp_client_connection.py
This PR implements the test requirements for issue #12: "Add test for basic tool execution via MCP client".
- **Replaced** the basic `test_client_can_call_tool` method with a comprehensive `test_basic_tool_execution_via_mcp_client` method
- **Implemented** all three acceptance criteria from issue #12:
1. ✅ Test executes at least one tool successfully (using `time_tool`)
2. ✅ Test verifies tool response format (validates MCP TextContent structure)
3. ✅ Test includes basic error case (invalid tool name)
- Uses `time_tool` as the primary test tool (simple, reliable, no external dependencies)
- Validates proper MCP response structure with `content` attribute
- Verifies TextContent format with `type` and `text` attributes
- Confirms time tool returns expected time format (`YYYY-MM-DD …
=> Add test for basic tool execution via MCP client (Issue #12)

.cursor/rules/github_issue_workflow.mdc
This PR improves the GitHub Issue Workflow documentation by combining separate `git checkout main` and `git pull origin main` commands into a single, more efficient command using the `&&` operator.
- **Pre-Work Setup section**: Combined commands into `git checkout main && git pull origin main`
- **Git Commands Reference section**: Updated for consistency
- **Cleanup section**: Applied the same improvement
- **Improved efficiency**: Reduces the number of commands from 2 to 1
- **Maintains safety**: The `&&` operator ensures `git pull` only executes if `git checkout` succeeds
- **Better consistency**: All git command examples now follow the same pattern
- **Cleaner documentation**: Reduces verbosity while maintaining clarity
- Verified the combined command works correctly in local testing
- …
=> docs: combine git checkout and pull commands using && operator

config/env.template, config/manager.py, config/tests/test_manager.py, config/types.py
Fixes #33
This PR implements support for multiple named git roots while maintaining full backward compatibility with the existing single `GIT_ROOT` configuration. This enables users to work with multiple repositories simultaneously in multi-project environments.
✅ **Multiple Named Git Roots**: Support environment variables like `GIT_ROOT_PROJECT_A`, `GIT_ROOT_PROJECT_B`, etc.  
✅ **Backward Compatibility**: Maintain support for the existing `GIT_ROOT` variable  
✅ **Dynamic Discovery**: Allow tools to query available git roots and select the appropriate one  
✅ **Parameter Substitution**: Enable command templates to use `{git_root_project_a}` placeholders  
- ✅ Support multiple git root environment variables with pattern `GIT_ROOT_<PROJECT_NAME>`
- ✅ Maintain backward compatibility with …
=> feat: Add support for multiple git roots/project routes

mcp_tools/tests/test_yaml_tool_base.py, mcp_tools/yaml_tools.py
This PR implements comprehensive unit tests for the `YamlToolBase` class as requested in issue #46. The implementation includes 56 test cases organized into 9 test classes, providing thorough coverage of all public methods, properties, and edge cases.
1. **TestYamlToolBaseInitialization** (8 tests)
- Tool initialization with different parameter combinations
- Missing parameters and fallback behavior
- Class attribute handling and parameter overrides
- Dependency injection during initialization
2. **TestYamlToolBaseProperties** (6 tests)
- Property getters: `name`, `description`, `input_schema`
- Default value handling and validation
- Malformed data handling
3. **TestYamlToolBaseToolTypeHandling** (3 tests)
- Default and custom tool type validation
- Tool type property behavior
4. …
=> feat: Add comprehensive unit tests for YamlToolBase class

.cursor/rules/generate_github_issue.mdc
This PR updates the GitHub issue creation cursor rules to include a standardized categorization format using square brackets at the beginning of issue titles.
- **Enhanced Title Format**: Added requirement for square bracket categorization at the beginning of issue titles
- **Comprehensive Categories**: Included examples for `[Feature]`, `[Bug]`, `[Chore]`, `[Tooling]`, `[Docs]`, `[Enhancement]`, `[API]`, `[Security]`, `[Performance]`, `[UI/UX]`, `[Database]`, `[Testing]`, `[DevOps]`, `[Research]`, etc.
- **Practical Examples**: Added three concrete examples showing proper title formatting:
- `[Feature] Add user authentication with OAuth2 support`
- `[Chore] Refactor database connection pooling logic`
- `[Tooling] Set up automated dependency vulnerability scanning`
- **Better …
=> [Tooling] Update GitHub issue title format with category brackets

scripts/logcompress_cli.py, utils/__init__.py, utils/logcomp/__init__.py, utils/logcomp/compressor.py, utils/logcomp/parsers.py, utils/logcomp/tests/__init__.py, utils/logcomp/tests/test_parsers.py, utils/logcomp/types.py
This PR refactors the `scripts/logcompress_cli.py` file into a proper utils module following the established project patterns. The refactoring separates core functionality from CLI interface, fixes import issues, and makes the log compression functionality reusable throughout the codebase.
- **`utils/logcomp/`** - New module directory following existing utils pattern
- **`utils/logcomp/__init__.py`** - Module exports with proper `__all__` definition
- **`utils/logcomp/types.py`** - Data structures and type definitions
- **`utils/logcomp/parsers.py`** - Log parser implementations with graceful dependency handling
- **`utils/logcomp/compressor.py`** - Core log compression functionality
- **`utils/logcomp/tests/`** - Basic test coverage
- **`scripts/logcompress_cli.py`** - Refactored to be a …
=> Refactor logcompress_cli.py into utils/logcomp module

scripts/segmenter_cli.py, utils/segmenter/__init__.py, utils/segmenter/cli_args.py, utils/segmenter/py.typed, utils/segmenter/tests/__init__.py, utils/segmenter/tests/test_workflow.py, utils/segmenter/types.py, utils/segmenter/workflow.py
This PR refactors the `scripts/segmenter_cli.py` file into a proper utils module at `utils/segmenter/`, addressing issue #71.
- **`utils/segmenter/workflow.py`** - Core segmentation workflow logic
- **`utils/segmenter/types.py`** - Type definitions and data structures  
- **`utils/segmenter/cli_args.py`** - CLI argument parsing and validation
- **`utils/segmenter/__init__.py`** - Module exports following existing patterns
- **`utils/segmenter/tests/`** - Comprehensive test suite
- Fixed linter error with `persist_directory` handling using proper `getattr`/`setattr` pattern
- Improved type safety throughout the module
- CLI interface remains exactly the same
- All existing functionality preserved
- Same command-line arguments and behavior
- Added comprehensive tests for core workflow …
=> Refactor segmenter_cli.py into utils/segmenter module

mcp_tools/tests/test_yaml_dynamic_classes.py
This PR implements comprehensive tests for dynamic YAML tool class creation and registration as requested in issue #50.
**✅ Clean Branch:** This PR is based purely on the latest main branch with only the test file changes for issue #50.
- `mcp_tools/tests/test_yaml_dynamic_classes.py` - New comprehensive test file (789 lines, 24 test cases)
- ✅ Class creation using `type()` with proper inheritance
- ✅ Class attribute setting (`_tool_name`, `_tool_data`)
- ✅ Class naming conventions (`YamlTool_{name}`)
- ✅ Class instantiation and validation
- ✅ Multiple class creation from multiple tool definitions
- ✅ Registration with `@register_tool(source="yaml")` decorator
- ✅ Integration with plugin registry
- ✅ Tool source tracking and metadata
- ✅ Registration error handling
- ✅ Instantiation …
=> Add comprehensive tests for dynamic YAML tool class creation and registration

mcp_tools/dependency.py, mcp_tools/plugin.py, server/main.py, server/startup_tracer.py
Fixes #17 (Phase 1 of 3-phase solution)
Implement comprehensive startup performance tracing to identify bottlenecks in MCP server initialization, as outlined in Issue #17.
- **Primary Bottleneck Identified**: Tool Discovery and Registration consumes **97-98%** of startup time
- **Current Startup Time**: ~0.25-0.33 seconds (already under 10s target, but can be optimized further)
- **Tool Count**: 22 tools discovered during startup
- **Secondary Operations**: All other operations are already well-optimized
- **Created `server/startup_tracer.py`**: Comprehensive performance tracing utility
- `TimingEntry` dataclass for measurements
- `StartupTracer` class with context managers and analysis
- Global functions and decorators (`@time_startup_operation`)
- JSON report …
=> Phase 1: Add comprehensive startup performance tracing (Issue #17)

.cursor/rules/github_issue_workflow.mdc
This PR enhances the GitHub issue workflow by adding a mandatory pre-submission code review phase to ensure higher code quality and prevent problematic code from reaching the pull request stage.
- Added mandatory automated code review step before PR creation
- Implemented quality gate decision process (PROCEED/STOP)
- Clear instructions to **NOT create PR** if review results are poor
- Detailed user notification requirements for poor review results
- Added code review results documentation template
- Updated output format sections to include review status
- Renumbered subsequent workflow phases (PR Phase → Phase 6, Post-Submission → Phase 7)
- Added "Pre-Submission Review" and "Quality Gates" to best practices
- Renumbered existing practices to accommodate new …
=> Enhance GitHub workflow: Add mandatory code review before PR submission

mcp_tools/tests/test_yaml_error_handling.py
This PR implements comprehensive error handling and edge case tests for the YAML tool system as requested in issue #51.
Created a comprehensive test suite with **48 tests** covering all error scenarios mentioned in the issue:
1. **Command Executor Error Scenarios (7 tests)**
- Missing or unavailable command executor
- Command execution failures and timeouts
- Async operation errors and token management
- Permission and access errors during execution
2. **Configuration and Validation Errors (6 tests)**
- Invalid tool configurations
- Missing required environment variables
- Malformed input schemas and validation failures
- Tool enablement/disablement edge cases
3. **File System and I/O Errors (7 tests)**
- File permission errors during YAML loading
- Disk space and I/O errors
- YAML …
=> Add comprehensive error handling and edge case tests for YAML tools

mcp_tools/tests/fixtures/test_fixtures.py, mcp_tools/tests/test_code_tools_coverage.py, mcp_tools/tests/test_code_tools_enhanced.py, pyproject.toml, uv.lock
This PR addresses issue #99 by implementing comprehensive test coverage for all code-based tools registered through the `mcp_tools.plugin.registry` system.
- **8 comprehensive tests** covering:
- Tool discovery and registration through plugin registry
- Tool instantiation and metadata validation  
- Tool execution with mocked dependencies
- Registry integration and filtering by source
- Duplicate name detection
- Coverage summary reporting
- **10 advanced tests** covering:
- Category-based tool analysis and execution
- Schema quality validation and scoring
- Dependency injection integration testing
- Comprehensive tool statistics and reporting
- Tool categorization across different domains
- Comprehensive mock system for external dependencies:
- `subprocess.run` and …
=> Add comprehensive test coverage for code-based tools (Issue #99)

.cursor/rules/github_issue_workflow.mdc
This PR improves the GitHub issue workflow documentation by adding guidance on marking issues as work-in-progress (WIP) before starting implementation.
- **Added WIP marking requirement**: Issues must be marked as work-in-progress immediately after creating a branch and before making code changes
- **Provided multiple WIP approaches**: 
- Adding "work-in-progress" or "WIP" labels
- Commenting on the issue to indicate work has started
- Assigning yourself to the issue
- **Updated progress tracking template**: Added WIP status field to the implementation progress section
- **Improved team coordination**: Prevents duplicate work and improves visibility of active development
- **Prevents duplicate work**: Team members can see when someone is actively working on an issue
- **Improves …
=> Improve GitHub issue workflow: Add WIP marking guidance

mcp_tools/tests/test_tool_argument_validation.py
This PR implements comprehensive tool argument validation testing as requested in issue #102.
- **New test file**: `mcp_tools/tests/test_tool_argument_validation.py`
- **Comprehensive test coverage** for tool argument validation including:
- Required field validation
- Type validation 
- Enum validation
- Schema compliance validation
- Test data generation utilities
- Automatically generates valid arguments based on JSON schemas
- Creates invalid test cases for validation testing
- Handles various data types (string, integer, number, boolean, array, object)
- Supports enum validation
- Generates contextually appropriate test values (URLs, emails, paths, etc.)
- **test_tool_argument_validation_comprehensive**: Tests all registered tools with both valid and invalid arguments
- …
=> Add comprehensive tool argument validation testing (Issue #102)

mcp_tools/tests/test_command_executor_async.py
Fixes #127 - Test failure where CommandExecutor test expects limited process status values but psutil returns "disk-sleep" on Linux systems.
The test `TestCommandExecutorAsync.test_list_running_processes_with_processes` was failing because it only accepted `["running", "sleeping"]` process status values, but psutil can return additional status values like `"disk-sleep"` on Linux systems when processes are waiting for I/O operations.
Updated the failing test assertion at line 444 to include `"disk-sleep"` status:
```python
assert process_info["status"] in ["running", "sleeping"]
assert process_info["status"] in ["running", "sleeping", "disk-sleep"]
```
This makes the test consistent with other tests in the same file that already handle the broader range of …
=> Fix issue #127: Update test assertion to accept disk-sleep process status

mcp_tools/plugin.py, server/main.py
This PR implements comprehensive plugin loading visibility during MCP server startup as requested in issue #159.
- Added emoji-based logging indicators for better visual clarity
- Plugin directory scanning now shows which directories are being processed
- Lists discovered plugin directories with clear formatting
- Early return with informative message when no plugins are found
- Each plugin loading operation is now logged with timing information
- Shows tool modules found within each plugin
- Displays success/failure status for each module loading attempt
- Tracks number of tools successfully registered per module
- Comprehensive error reporting for failed plugin loads
- Tracks plugins discovered, loaded successfully, and failed
- Per-directory summary …
=> Fix issue #159: Add detailed plugin loading visibility during server startup

.cursor/rules/github_issue_workflow.mdc
This PR adds repository identification instructions to the GitHub issue workflow, similar to the generate GitHub issue workflow.
- Added a simple repository identification instruction: `git remote -v` to identify the correct repository owner and name before any GitHub operations
- Updated the git commands reference to include the repository verification step
- Updated best practices to include repository verification as the first step
This ensures consistency between the generate GitHub issue workflow and the GitHub issue workflow, preventing issues with incorrect repository targeting during PR creation, issue commenting, or other GitHub operations.
- Verified the workflow file syntax and formatting
- Confirmed the changes maintain the concise style requested …
=> [Chore] Add repository identification to GitHub issue workflow

.gitignore, utils/secret_scanner/scanner.py, utils/secret_scanner/tests/fixtures/msbuild_vcx_example.txt, utils/secret_scanner/tests/fixtures/taef_clean_example.txt, utils/secret_scanner/tests/test_msbuild_detection.py, utils/secret_scanner/tests/test_msbuild_integration.py, utils/secret_scanner/tests/test_msbuild_taef_comprehensive.py
This PR adds comprehensive test cases for MSBuild and TAEF (Test Authoring and Execution Framework) output with the secret scanner to ensure proper handling of build tool outputs.
- `utils/secret_scanner/tests/test_msbuild_taef_comprehensive.py` - **16 comprehensive test cases**
- `utils/secret_scanner/tests/fixtures/taef_clean_example.txt` - TAEF output fixture
- `utils/secret_scanner/tests/test_msbuild_detection.py` - MSBuild detection tests
- `utils/secret_scanner/tests/test_msbuild_integration.py` - MSBuild integration tests
- `utils/secret_scanner/tests/fixtures/msbuild_vcx_example.txt` - MSBuild output fixture
- Updated `.gitignore` to properly handle secret scanner files while ignoring `__pycache__` directories
- Added specific exceptions for `utils/secret_scanner/` directory
- ✅ …
=> Add comprehensive MSBuild and TAEF test cases for secret scanner

config/env.template, config/manager.py, plugins/azrepo/tests/test_workitem_create.py, plugins/azrepo/tests/test_workitem_rest_api.py, plugins/azrepo/workitem_tool.py
This PR adds support for parsing bearer tokens from command line output instead of requiring hardcoded tokens in the `.env` configuration file.
- **`AZREPO_BEARER_TOKEN_COMMAND`**: Execute a command and extract the `accessToken` from JSON output
- Maintains backward compatibility with existing `AZREPO_BEARER_TOKEN` static configuration
- Static token takes precedence if both are configured
- Added `_execute_bearer_token_command()` method in `EnvironmentManager`
- Enhanced `get_azrepo_parameters()` to dynamically resolve bearer tokens
- Proper error handling with logging and 30-second timeout
- Command must output valid JSON with an `accessToken` property
- Updated `config/env.template` with examples and documentation
- Added example Azure CLI command: `az account get-access-token …
=> feat: Add support for dynamic bearer token from command output

server/main.py, server/templates/base.html, server/templates/tool_history.html
This PR implements a comprehensive web interface for tool execution history as requested in issue #152.
✅ **New `/tool-history` page** accessible from main navigation  
✅ **Paginated table view** of tool execution history  
✅ **Basic filtering** by tool name, success status, and date range  
✅ **Detail modal/view** for individual tool executions  
✅ **Statistics overview dashboard** with key metrics  
✅ **Visual indicators** for success/failure status  
✅ **Export functionality** for history data (JSON/CSV)  
✅ **Responsive design** that works on mobile devices  
✅ **Consistent styling** with existing web interface  
✅ **Error handling** and user feedback for API failures  
✅ **Loading states** and progress indicators  
1. **New Template**: …
=> Implement tool execution history web interface

mcp_tools/tests/test_plugin_config.py
This PR adds comprehensive test coverage for the `MCP_EXCLUDED_TOOL_NAMES` environment variable as requested in issue #145.
- ✅ Empty string handling
- ✅ Whitespace-only input handling  
- ✅ Empty comma-separated values (e.g., `tool_a,,tool_b`)
- ✅ Leading/trailing commas
- ✅ Single comma input
- ✅ Case sensitivity verification
- ✅ Special characters in tool names (dashes, underscores, dots)
- ✅ Unicode character support (émojis, 中文)
- ✅ Very long lists (100+ tools)
- ✅ Integration with plugin registry
- ✅ Multiple tool exclusion
- ✅ Partial exclusion scenarios
- ✅ Interaction with YAML tools
- ✅ Precedence over YAML override logic
- ✅ Interaction with base class exclusion
- ✅ Environment variable reloading
- ✅ Excluding non-existent tools doesn't …
=> Add comprehensive test coverage for MCP_EXCLUDED_TOOL_NAMES environment variable

mcp_tools/command_executor/executor.py, server/api.py, server/templates/jobs.html
This PR implements the enhancement requested in issue #173 to separate background jobs into two distinct tables and preserve start times for completed jobs.
**Developed using:** Cursor
- **Modified `CommandExecutor.wait_for_process()`** in `mcp_tools/command_executor/executor.py`:
- Added `start_time` preservation in completed process results
- Ensures chronological ordering capability for completed jobs
- **Updated `api_list_background_jobs()`** in `server/api.py`:
- Improved handling of `start_time` for completed jobs
- Simplified logic for backward compatibility
- **Split jobs page into two distinct tables** in `server/templates/jobs.html`:
- **Active Jobs Table**: Shows only running jobs with real-time updates
- **Job History Table**: Shows completed/failed/terminated jobs with …
=> Fix issue #173: Separate jobs into Active and History tables with preserved start times

plugins/azrepo/workitem_tool.py
This PR updates the Azure DevOps work item tool with improved authentication handling and REST API support for better reliability and functionality.
- Enhanced authentication with bearer token command support
- Improved REST API integration for work item creation
- Better error handling and logging
- Updated configuration management
- Code has been tested with the existing Azure DevOps integration
- Authentication flows verified for both static and dynamic token scenarios
=> Update Azure DevOps work item tool with improved authentication and REST API support

mcp_tools/concurrency_manager.py, mcp_tools/tests/test_concurrency_manager.py, mcp_tools/yaml_tools.py, server/tools.yaml
This PR implements pull request YAML configuration concurrency limits as requested in issue #187. The feature provides a simple, robust way to control concurrent operations for any YAML-defined tool to prevent resource conflicts, API rate limiting, and performance issues.
- **`ConcurrencyManager`**: Thread-safe manager for tracking and limiting concurrent operations
- **`ConcurrencyConfig`**: Simple configuration with `max_concurrent` setting
- **`OperationContext`**: Context tracking for individual operations
- **Global instance management**: Singleton pattern for shared concurrency control
- **Automatic loading**: Concurrency configs are loaded from YAML tool definitions
- **Seamless integration**: Works with existing YAML tool loading process
- **Example …
=> feat: implement pull request YAML configuration concurrency limits

plugins/azrepo/tests/test_workitem_create.py, plugins/azrepo/workitem_tool.py
This PR fixes two failing tests in the Azure DevOps repository plugin related to bearer token authentication logic.
1. **Bearer token command precedence**: The `_get_auth_headers` method was checking the instance `self.bearer_token` (set during initialization) before checking for dynamic bearer token commands, preventing dynamic tokens from taking precedence over static tokens.
2. **Error handling in tests**: The test for missing bearer token configuration was not properly clearing the instance bearer token, causing the test to fail to raise the expected `ValueError`.
- **Fixed `_get_auth_headers` method**: 
- Always get fresh parameters from environment manager first
- Check bearer token command first (takes precedence)
- Fall back to static token from environment
- Finally fall back to …
=> Fix azrepo bearer token authentication precedence and error handling

.github/workflows/tests.yml
This PR fixes the GitHub Actions workflow to prevent canceling parallel matrix jobs when one job fails, ensuring we get complete test results from all platforms.
Currently, the GitHub Actions workflow uses a matrix strategy to run tests on multiple operating systems (Ubuntu and Windows) in parallel. However, by default, GitHub Actions has `fail-fast: true`, which means:
- ❌ If the Ubuntu job fails, the Windows job gets canceled (or vice versa)
- ❌ We lose valuable test information from the other platforms
- ❌ Debugging becomes harder since we can't see if the issue is platform-specific
- ❌ CI becomes less reliable for comprehensive testing
Added `fail-fast: false` to the strategy configuration, which ensures:
- ✅ **All matrix jobs run to completion** regardless …
=> Fix GitHub Actions to not cancel parallel jobs on failure

server/main.py, server/tests/conftest.py
This PR fixes critical test case failures that were preventing the server tests from running successfully.
1. **ImportError for PERSIST_DIR**: Fixed import path from `server.api` to `server.api.base` in `server/main.py`
2. **Missing environment configuration**: Added comprehensive environment variables to test configuration in `server/tests/conftest.py`
- Changed import from `from server.api import PERSIST_DIR` to `from server.api.base import PERSIST_DIR`
- Resolves the ImportError that was preventing server startup
- Added comprehensive environment variable setup in the `mcp_server` fixture
- Includes all required configuration variables: GIT_ROOT, PROJECT_NAME, TOOL_HISTORY_ENABLED, VECTOR_STORE_PATH, etc.
- Ensures tests have proper environment setup without …
=> Fix test case failures: Import error and environment configuration

server/api/background_jobs.py, server/main.py, server/tests/conftest.py
This PR fixes failing background jobs API tests by resolving an issue where YAML-defined tools (like `execute_task`) were not being loaded during test execution.
The `test_background_job_lifecycle` test was failing because the `execute_task` tool was not found during test execution. Investigation revealed that YAML-based tools were not being loaded in the test environment due to incorrect YAML tool path configuration.
The YAML tool discovery system looks for `tools.yaml` files in paths determined by the `get_yaml_tool_paths()` method:
1. `PRIVATE_TOOL_ROOT` environment variable
2. `MCP_YAML_TOOL_PATHS` environment variable  
3. Default paths: `server/.private`, `server`, and current directory
During tests, `PRIVATE_TOOL_ROOT` was set to the project root, but the …
=> Fix background jobs API tests: Enable YAML tool loading in test environment

plugins/azrepo/pr_tool.py, plugins/azrepo/tests/test_pull_requests.py
This pull request resolves issue #212 by switching the `list_pull_requests` function in the `azrepo` plugin to use the Azure DevOps REST API instead of the `az` CLI. This change improves performance and reduces the dependency on the Azure CLI.
The tests have been updated to mock the REST API calls and ensure the new implementation is working correctly.
=> feat(azrepo): Switch list_pull_requests to REST API

plugins/azrepo/workitem_tool.py
This PR updates the operation description in the Azure DevOps Work Item tool to clarify which operations are supported.
- Updated the `operation` parameter description in `plugins/azrepo/workitem_tool.py` to explicitly state "support get, create, update"
- This improves the tool's documentation and makes it clearer for users what operations are available
- **Code Editor:** Cursor
- **Branch:** `feature/update-workitem-tool`
- **Files Modified:** `plugins/azrepo/workitem_tool.py` (1 line changed)
This is a documentation-only change that doesn't affect functionality. The change clarifies the existing supported operations without modifying any logic.
=> Update workitem tool operation description to clarify supported operations

plugins/azrepo/pr_tool.py, plugins/azrepo/tests/test_pull_requests.py
This PR converts three Azure DevOps pull request methods from CLI commands to REST API calls for improved performance and reliability.
- ✅ Converted to use PATCH `/git/repositories/{repo}/pullrequests/{id}` endpoint
- ✅ Maintains exact same method signature and return format
- ✅ Supports all parameter combinations (title, description, status, draft, auto_complete, squash, delete_source_branch)
- ✅ Proper handling of completion options and auto-complete settings
- ✅ Comprehensive error handling and logging
- ✅ Converted to use PUT `/git/repositories/{repo}/pullrequests/{id}/reviewers/{reviewerId}` endpoint
- ✅ Implements proper vote value mapping (approve=10, approve-with-suggestions=5, reset=0, wait-for-author=-5, reject=-10)
- ✅ Validates vote values and provides clear error messages
- ✅ …
=> Convert Azure PR methods from CLI to REST API

plugins/azrepo/pr_tool.py, plugins/azrepo/tests/test_pull_requests.py
Fixes #239
This PR implements improved default behavior for the Azure DevOps Pull Request tool's `list_pull_requests` operation to provide better user experience for common developer workflows.
- **Default status filtering**: Changed from `None` to `"active"` - only shows open, actionable PRs by default
- **Default target branch filtering**: Smart default to `"main"` or configured default branch for better focus
- **Draft PR filtering**: New `exclude_drafts` parameter (default: `True`) filters out work-in-progress draft PRs
- Explicit `None` values preserve old behavior (no filtering)
- All existing API calls continue to work unchanged
- Added comprehensive tests for backward compatibility scenarios
- Added `exclude_drafts` parameter with clear documentation
- …
=> Fix issue #239: Improve default PR listing behavior with smart filtering

plugins/azrepo/pr_tool.py, plugins/azrepo/tests/test_pull_requests.py
This PR fixes the PR tool authentication and HTTP client usage issues identified in #247.
- ✅ **Replaced 11 instances** of `self._get_auth_headers()` with `get_auth_headers()` from `azure_rest_utils`
- ✅ **Removed backward compatibility method** usage in favor of the correct centralized authentication
- ✅ **Replaced 11 instances** of `aiohttp.ClientSession()` with `AzureHttpClient()` from `azure_rest_utils`
- ✅ **Updated imports** to include `AzureHttpClient` from `azure_rest_utils`
- ✅ **Removed aiohttp import** as it's no longer needed
- ✅ **Improved error handling** with standardized response format from centralized client
All HTTP operations in the PR tool now use the centralized approach:
1. `list_pull_requests` - GET requests
2. `get_pull_request` - GET requests  
3. …
=> Fix PR tool authentication and HTTP client usage

plugins/azrepo/pr_tool.py, plugins/azrepo/tests/test_pull_requests.py
Fixes the default behavior of the pull request list functionality to properly filter by the current user's PRs instead of returning all PRs.
The default behavior of `list_pull_requests()` with `creator="default"` was incorrectly returning all PRs instead of filtering by the current user. This happened because:
1. **Local username vs Azure DevOps identity mismatch**: The code was using the local system username (e.g., "john.doe") directly as the creator filter
2. **Azure DevOps expects email/identity**: The API expects an Azure DevOps user identifier (typically email like "john.doe@company.com")  
3. **Silent failure**: When the filter didn't match any user, Azure DevOps returned all PRs instead of an empty result
- **Added identity resolution**: When …
=> Fix PR list creator filtering: Resolve local username to Azure DevOps identity

.pre-commit-config.yaml, .secrets.baseline, utils/secret_scanner/cli.py, utils/secret_scanner/scanner.py
This PR improves the secret scanner utility by adding proper error handling for the `detect-secrets` dependency and creating a CLI module for pre-commit hook integration.
- Wrapped `detect-secrets` imports in try-except block
- Added informative error message when package is not installed
- Guides users to source the virtual environment if needed
- Prevents cryptic import errors during secret scanning operations
- Created new CLI interface for the secret scanner
- Provides command-line access to secret scanning functionality
- Supports verbose output and file scanning
- Integrates with pre-commit hooks for automated secret detection
- Updated custom secret scanner hook to use `uv run python` instead of `python`
- Added proper PYTHONPATH configuration for module …
=> Fix: Add error handling for detect-secrets import and CLI module

.cursor/environment.json
This PR adds a Cursor environment configuration file (`.cursor/environment.json`) that specifies `uv sync` as the install command for the project.
- **Code Editor:** Cursor
- Added `.cursor/environment.json` with configuration to use `uv sync` for dependency installation
- This ensures Cursor uses the correct package manager (uv) instead of defaulting to pip
- Improves developer experience in Cursor by automatically using the correct package manager
- Ensures consistency with the project's dependency management approach using uv
- Reduces setup friction for new developers using Cursor
- **Code Editor:** Cursor
- **Test Framework:** Manual validation
- **Total Tests Run:** Environment validation
- **Test Results:** All passed
- **Integration Testing:** Completed - `uv run python --version` …
=> Add Cursor environment configuration for uv sync

plugins/azrepo/azure_rest_utils.py, scripts/azure_identity_cli.py
This PR implements a comprehensive CLI tool for Azure DevOps identity resolution, exposing the functionality from `azure_rest_utils.py` as a command-line interface.
- **`scripts/azure_identity_cli.py`** - Complete CLI tool with the following features:
- Single and batch identity resolution
- Support for both static bearer tokens (`AZREPO_BEARER_TOKEN`) and command-based authentication (`AZREPO_BEARER_TOKEN_COMMAND`)
- JSON and human-readable output formats
- File-based batch processing
- Authentication testing functionality
- Comprehensive error handling and help documentation
1. **Identity Resolution**
- Resolve single identities: `azure_identity_cli.py resolve --organization myorg john.doe@company.com`
- Batch processing from files: `azure_identity_cli.py resolve --organization myorg …
=> feat: Add Azure identity resolution CLI tool

config/neo4j.yaml, pyproject.toml, utils/graph_interface/__init__.py, utils/graph_interface/config.py, utils/graph_interface/exceptions.py, utils/graph_interface/models.py, utils/graph_interface/neo4j_client.py, utils/graph_interface/tests/__init__.py, utils/graph_interface/tests/test_config.py, utils/graph_interface/tests/test_models.py, uv.lock
This PR implements the complete Neo4j Graph Interface Core Infrastructure as specified in issue #273. The implementation provides a decoupled, reusable Neo4j graph interface that can be used by various components for managing relationships and dependencies.
- Added `neo4j>=5.15.0` for Neo4j Python driver
- Added `typing-extensions>=4.8.0` for enhanced typing support
```
utils/graph_interface/
├── __init__.py              # Main module exports
├── exceptions.py            # Custom exception classes
├── models.py               # Pydantic data models
├── config.py               # Configuration management
├── neo4j_client.py         # Async Neo4j client
└── tests/                  # Comprehensive test suite
├── __init__.py
├── test_models.py
└── …
```
=> Implement Neo4j Graph Interface Core Infrastructure

pyproject.toml, utils/graph_interface/algorithms.py, utils/graph_interface/analytics.py, utils/graph_interface/graph_manager.py, utils/graph_interface/tests/test_algorithms.py, utils/graph_interface/tests/test_analytics.py, utils/graph_interface/tests/test_graph_manager.py, uv.lock
Resolves #275
Implements comprehensive graph interface with GraphManager, GraphAnalytics, and GraphAlgorithms classes.
Features: graph statistics, path finding, traversal algorithms, community detection, centrality measures.
Testing: 59 new tests, all 274 tests passing.
Quality: GDS integration with fallbacks, comprehensive error handling.
=> Implement High-Level Graph Manager (Issue #275)

.github/workflows/tests.yml, scripts/run_component_group.sh, scripts/run_tests.sh
This PR implements a comprehensive optimization of the GitHub Actions CI pipeline, reducing execution time by **75%** through parallel matrix strategy.
| Metric | Before | After | Improvement |
|--------|--------|-------|-------------|
| **Execution Time** | ~40 minutes | ~8 minutes | **75% faster** |
| **Parallel Runners** | 2 (sequential) | 12 (parallel) | **6x more runners** |
| **Resource Utilization** | Poor | Excellent | **Much better** |
| **Feedback Speed** | Slow | Fast | **Immediate failure detection** |
- Split 14 test components into 6 logical groups
- Each group runs on separate virtual machines simultaneously
- Both Ubuntu and Windows tested in parallel (12 total runners)
- **core-group**: config, mcp_core, mcp_tools
- **server-group**: server, project tests
- …
=> Optimize CI pipeline performance with parallel matrix strategy

utils/graph_interface/examples/__init__.py, utils/graph_interface/examples/basic_usage.py, utils/graph_interface/examples/task_example.py, utils/graph_interface/integration/__init__.py, utils/graph_interface/integration/command_executor.py, utils/graph_interface/scheduling/__init__.py, utils/graph_interface/scheduling/task_scheduler.py, utils/graph_interface/visualization/__init__.py, utils/graph_interface/visualization/mermaid_generator.py
This PR implements comprehensive task management integration and usage examples for the Neo4j graph interface, addressing issue #276.
- **TaskExample**: Advanced task management examples including:
- Basic task creation and dependency modeling
- Complex CI/CD workflow scenarios with parallel tasks
- Resource constraint management and conflict detection
- Priority-based scheduling with deadline awareness
- Error handling with fallback tasks and recovery scenarios
- **BasicUsageExample**: Simple, introductory examples for new users
- **TaskScheduler**: Comprehensive scheduling engine with:
- Ready task identification (tasks with no blocking dependencies)
- Circular dependency detection and prevention
- Critical path calculation for project planning
- Resource conflict detection and …
=> feat: implement task management integration and usage examples for Neo4j graph interface

.claude/CLAUDE.md, mcp_core/tests/run_tests.py, mcp_tools/tests/run_tests.py, scripts/install.sh, scripts/run_component_group.sh, utils/__init__.py, utils/memory/__init__.py, utils/memory/context_memory.py, utils/memory/conversation_memory.py, utils/memory/memory_manager.py, utils/memory/py.typed, utils/memory/tests/__init__.py, utils/memory/tests/run_tests.py, utils/memory/tests/test_context_memory.py, utils/memory/tests/test_conversation_memory.py, utils/memory/tests/test_memory_manager.py, utils/memory/tests/test_types.py, utils/memory/types.py
The branch feature/test-execution-updates has been pushed with your 3 commits:
- 336b971 - refactor: update test execution commands to use 'uv' for consistency
- 447d89a - feat: introduce memory management module for LLM applications
- 5c2e4aa - docs: add additional instructions for Python execution and package management
=> Feature/test execution updates (Claude Code)

.github/workflows/vscode-extension-ci.yml, wu-wei/.eslintrc.json, wu-wei/CHANGELOG.md, wu-wei/package-lock.json, wu-wei/package.json, wu-wei/src/test/README.md, wu-wei/src/test/runTest.ts, wu-wei/src/test/suite/extension.test.ts, wu-wei/src/test/suite/index.ts, wu-wei/tsconfig.json
- Updated package.json to include test scripts and dependencies for testing.
- Created README.md for test structure and guidelines.
- Implemented runTest.ts as the test runner for the extension.
- Added extension.test.ts with basic tests for activation, configuration, and command registration.
- Created index.ts to manage and run Mocha tests.
- Updated tsconfig.json to include types for Mocha and Node, and enabled JSON module resolution.
=> feat(tests): add initial test suite and configuration

GEMINI.md
This PR updates the GEMINI.md file with instructions for creating pull requests.
Editor: gemini-cli
=> docs: update GEMINI.md with PR instructions (Gemini)

.prompts/extract_commit_info.prompt.md, .prompts/generate_github_issue.prompt.md, .prompts/github_issue_planning.prompt.md, .prompts/github_issue_workflow.prompt.md
- Introduced new markdown files for extracting key information from commits, generating GitHub issues, and planning GitHub issue workflows.
- These prompts enhance project management and code analysis capabilities, providing structured guidelines for issue creation and dependency management.
- The new documentation supports better coordination and clarity in development processes.
=> feat: Add prompts for commit analysis and GitHub issue management

wu-wei/src/interfaces/agentInterface.ts, wu-wei/src/providers/agentPanelProvider.ts, wu-wei/src/webview/agent/index.html, wu-wei/src/webview/agent/main.js
refactor: streamline prompt handling and remove unused input mode
Created by: gemini-cli
=> refactor: streamline prompt handling and remove unused input mode (Gemini)

.prompts/submit.prompt.md, wu-wei/src/promptStore/PromptStoreProvider.ts, wu-wei/src/providers/BaseWebviewProvider.ts, wu-wei/src/test/integration/fileSystem/fileSystem.test.ts, wu-wei/src/test/integration/promptStore/provider.test.ts, wu-wei/src/webview/promptStore/index.html, wu-wei/src/webview/promptStore/main.js, wu-wei/src/webview/promptStore/style.css
This PR refactors the `PromptStoreProvider` class to inherit from the `BaseWebviewProvider` class, improving code reusability and maintainability across webview providers in the Wu Wei VS Code extension.
- **PromptStoreProvider inheritance**: Changed `PromptStoreProvider` to extend `BaseWebviewProvider` instead of implementing `vscode.WebviewViewProvider` directly
- **Shared webview content generation**: Migrated to use the shared `getWebviewContent()` method from `BaseWebviewProvider`
- **Removed duplicate code**: Eliminated redundant webview initialization logic
- **Debug logging**: Added comprehensive debug logging for CSS and JS placeholder replacement in `BaseWebviewProvider`
- **Template variable tracking**: Improved visibility into webview content generation process
- **Submit …
=> refactor: migrate PromptStoreProvider to extend BaseWebviewProvider

wu-wei/docs/webview-resource-management.md, wu-wei/src/promptStore/PromptStoreProvider.ts, wu-wei/src/providers/BaseWebviewProvider.ts, wu-wei/src/providers/agentPanelProvider.ts, wu-wei/src/providers/debugPanelProvider.ts, wu-wei/src/providers/unifiedChatProvider.ts, wu-wei/src/webview/agent/index.html, wu-wei/src/webview/agent/main.js, wu-wei/src/webview/chat/index.html
This PR simplifies the Wu Wei agent panel interface by removing the input mode selection and always using the combined mode (prompt template + custom message). This change improves user experience by streamlining the interface and reducing complexity.
- **HTML (`wu-wei/src/webview/agent/index.html`)**:
- Removed input mode selector dropdown
- Always show prompt selector container
- Updated section subtitle to reflect combined mode usage
- Simplified UI structure
- **JavaScript (`wu-wei/src/webview/agent/main.js`)**:
- Set `promptMode` to always be `'combined'`
- Removed `promptModeSelector` DOM element and event handlers
- Simplified UI management functions to always use combined mode
- Updated `sendAgentRequest()` to always require both prompt and custom message
- Removed mode-specific …
=> refactor: simplify agent panel to use only prompt+custom message mode

wu-wei/src/shared/promptManager/index.ts, wu-wei/src/shared/promptManager/tsx/README.md, wu-wei/src/shared/promptManager/tsx/components/AgentPrompt.tsx, wu-wei/src/shared/promptManager/tsx/components/ContextDataMessage.tsx, wu-wei/src/shared/promptManager/tsx/components/ConversationHistoryMessages.tsx, wu-wei/src/shared/promptManager/tsx/components/SystemInstructionMessage.tsx, wu-wei/src/shared/promptManager/tsx/components/UserQueryMessage.tsx, wu-wei/src/shared/promptManager/tsx/components/index.ts, wu-wei/src/shared/promptManager/tsx/index.ts, wu-wei/src/shared/promptManager/tsx/tests/PromptHelpers.test.ts, wu-wei/src/shared/promptManager/tsx/types/AgentPromptProps.ts, wu-wei/src/shared/promptManager/tsx/types/index.ts, wu-wei/src/shared/promptManager/tsx/utils/index.ts, wu-wei/src/shared/promptManager/tsx/utils/promptHelpers.ts, wu-wei/src/shared/promptManager/types.ts
This PR implements a comprehensive set of TSX prompt components to replace string concatenation in agent interactions, as requested in issue #376.
- **AgentPrompt**: Main orchestrating component with priority-based composition and token budgeting
- **SystemInstructionMessage**: High-priority system prompts (priority 100, never pruned)
- **UserQueryMessage**: User input messages with high priority (priority 90)
- **ConversationHistoryMessages**: Chat history with configurable limits (priority 80)
- **ContextDataMessage**: Flexible context data with token allocation (priority 70)
- **PromptHelpers**: Utility class with token estimation, content sanitization, and formatting
- **TypeScript Interfaces**: Complete type definitions for all component props
- …
=> Implement TSX prompt components for agent interactions

.github/workflows/package-extension.yml
This PR enhances the `package-extension.yml` workflow to include automated version bumping after successful extension packaging, with full support for branch protection rules through pull request creation and auto-merge functionality.
- **Automated Version Bumping**: Automatically increments patch version after successful package build
- **Branch Protection Compliance**: Creates PRs instead of direct pushes to respect branch protection rules
- **Auto-Merge Integration**: Enables automatic merging with squash strategy once all checks pass
- **Comprehensive Git Configuration**: Proper git user setup for automated commits
- **Version Management**: Uses `npm version patch` to increment package.json version
- **Branch Strategy**: Creates dedicated `chore/bump-version-v{VERSION}` branches for …
=> feat(workflow): Add automated version bump with auto-merge PR capability

wu-wei/src/interfaces/agentInterface.ts, wu-wei/src/providers/agentPanelProvider.ts, wu-wei/src/shared/promptManager/tsx/components/AgentPrompt.tsx, wu-wei/src/test/integration/promptStore/agentPromptIntegration.test.ts
This PR resolves issue #378 by replacing basic string concatenation in `AgentPanelProvider` with sophisticated TSX-based prompt composition, implementing intelligent prioritization and token management.
- **Replaced string concatenation** in `AgentPanelProvider.enhanceParamsWithPrompt()` with TSX-based composition
- **Added `AgentPrompt` component** with priority-based message ordering and token budgeting
- **Implemented graceful fallback** from TSX to string concatenation for backward compatibility
- **Enhanced `AgentPrompt` component** with intelligent composition logic:
- System instructions (highest priority, never pruned)
- User query (very high priority)
- Recent conversation history (high priority, last 2 messages)
- Older conversation history (medium priority)
- Context data …
=> Replace string concatenation with TSX-based prompt composition in AgentPanelProvider

.github/workflows/daily-version.yml, .github/workflows/extension-ci.yml, .github/workflows/package-extension.yml, .github/workflows/tests.yml
Fixes workflow dispatch permission errors in package-extension.yml and daily-version.yml by removing manual test triggers and relying on automatic PR-triggered tests.
=> fix: resolve workflow dispatch HTTP 403 errors in automated workflows

.claude/settings.json
This PR introduces comprehensive permission configuration for Claude Code to enhance security while maintaining development flexibility.
- **Added ** with carefully configured permissions
- **Read/Edit Access**: Allow all files except sensitive  files
- **Command Execution**: Allow all bash commands except dangerous  operations  
- **Web Access**: Enable fetching from any domain for maximum flexibility
-  - Read access to all project files
-  - Edit access to all project files
-  - Execute any bash commands
-  - Fetch content from any web domain
-  &  - Block reading environment files
-  &  - Block editing environment files  
-  - Prevent destructive deletion commands
- **Enhanced Security**: Protects sensitive files and prevents destructive operations
- **Development Flexibility**: Broad …
=> feat: configure Claude Code permissions for enhanced security and flexibility

config/env.template, config/manager.py, plugins/kusto/README.md, plugins/kusto/tests/test_kusto_client.py, plugins/kusto/tests/test_kusto_dataframe_integration.py, plugins/kusto/tool.py
Integrates Kusto tool with DataFrame management framework for efficient handling of large query results.
- Auto-store DataFrames >1MB with interactive querying capabilities
- Added configuration options for DataFrame storage behavior  
- Enhanced result formatting with DataFrame IDs and summaries
- Comprehensive testing and documentation updates
- Maintains backward compatibility for small results
1. **feat: Implement Kusto DataFrame integration** - Core implementation with async DataFrame storage
2. **chore: Update threshold from 10MB to 1MB** - Better performance for smaller datasets  
3. **fix: Update format_results tests to async** - Fixed test failures caused by async method changes
✅ All 29 integration tests passing  
✅ Configuration system verified
✅ DataFrame storage logic working …
=> feat: Implement Kusto DataFrame integration (resolves #439)

plugins/kusto/tool.py
- Enhanced validation for database and cluster parameters in `KustoClient`.
- Ensures robust error handling and clearer configuration requirements for Kusto queries.
- All existing tests pass.
- Manual validation of KustoClient initialization and query execution.
- No breaking changes.
- No sensitive data included.
---
Auto-merge should be enabled after required checks pass.
=> feat(kusto): Enhance database and cluster validation in KustoClient

mcp_tools/kv_store/tool.py, mcp_tools/tests/test_kv_store.py
This pull request was created automatically to merge the latest committed changes from the temporary branch 'submit-temp-branch' into 'main', following repository rules that require all changes to main to go through a PR.
- All changes have been staged, committed, and pushed.
- Please review and merge if all checks pass.
This PR was created by the automated submit workflow.
=> [Auto-Submit] Merge changes from submit-temp-branch to main

mcp_tools/dataframe_service/tool.py, pyproject.toml, scripts/run_component_group.sh, scripts/submit.sh, server/api/dataframes.py, utils/dataframe_manager/query/processor.py, utils/dataframe_manager/tests/test_query_processor.py, utils/pyeval/__init__.py, utils/pyeval/evaluator.py, utils/pyeval/tests/__init__.py, utils/pyeval/tests/test_evaluator.py, uv.lock
This PR includes the following commits:
396a9a8 feat: Add submit.sh script for automated code submission workflow
90f05d3 feat: Integrate RestrictedPython for secure expression evaluation in DataFrame operations
- mcp_tools/dataframe_service/tool.py
- pyproject.toml
- scripts/run_component_group.sh
- scripts/submit.sh
- server/api/dataframes.py
- utils/dataframe_manager/query/processor.py
- utils/dataframe_manager/tests/test_query_processor.py
- utils/pyeval/__init__.py
- utils/pyeval/evaluator.py
- utils/pyeval/py.typed
- utils/pyeval/tests/__init__.py
- utils/pyeval/tests/test_evaluator.py
- uv.lock
🤖 Generated with automated submission script
=> feat: Add submit.sh script for automated code submission workflow

scripts/get_website_cookies.py
This PR adds a comprehensive website cookie extraction script that leverages the existing PlaywrightWrapper utility.
- **Multiple Browser Support**: Supports chromium, chrome, edge, firefox, and webkit browsers
- **Flexible Output Formats**: JSON, table, and simple text formats
- **Persistent Sessions**: Optional user data directory for maintaining login sessions
- **CLI Interface**: Comprehensive command-line interface with helpful options
- **File Export**: Ability to save cookies to JSON files
- **Error Handling**: Proper error handling and validation
```bash
python scripts/get_website_cookies.py https://example.com
python scripts/get_website_cookies.py https://example.com --browser chrome --no-headless
python scripts/get_website_cookies.py https://example.com --output json …
```
=> Add website cookie extraction script

server-ui/README.md, server-ui/src-tauri/Cargo.toml, server-ui/src-tauri/src/lib.rs, server-ui/src/main.ts, server-ui/src/styles.css
This PR enhances the server UI with comprehensive Tauri CLI integration and improved server readiness tracking. The changes provide users with clear installation instructions and better visual feedback during server startup.
- **Updated `server-ui/README.md`** with detailed Tauri CLI installation instructions
- Added troubleshooting section for common installation issues
- Included platform-specific installation commands for macOS, Linux, and Windows
- **Enhanced `server-ui/src/main.ts`** with robust server readiness monitoring
- Added new status indicators: starting, running, and stopped states
- Implemented better error handling and user feedback during server startup
- Added server status polling with appropriate timeouts
- **Updated `server-ui/src/styles.css`** with new status styling …
=> feat: Enhance server UI with Tauri CLI installation instructions and server readiness tracking

server-ui/src-tauri/src/lib.rs
This PR fixes a Windows-specific issue where starting the Tauri app would create an additional command window that wouldn't disappear when stopping the server.
Changes Made:
1. Added CREATE_NO_WINDOW flag to server startup command to prevent console window display
2. Improved Windows signal handling to target specific process group instead of all processes
3. Updated process creation flags to combine CREATE_NEW_PROCESS_GROUP with CREATE_NO_WINDOW
Technical Details:
- Fixed server command execution to use proper Windows process creation flags
- Improved signal handling for more targeted process termination
- Prevents unwanted console windows from appearing on Windows
Impact:
Resolves Windows-specific UI behavior where command windows persisted after stopping the server. The fix ensures …
=> fix: resolve Windows command window visibility issue

app/index.html, app/src/main.ts, app/src/styles.css
This PR adds a left sidebar navigation to the MCP Server Manager app with the following features:
- **Left Sidebar Navigation**: Added a responsive left panel with navigation items
- **Default 'Server Mgmt'**: The sidebar defaults to 'Server Mgmt' as the active view  
- **Future-Ready Structure**: Added placeholder 'Coming Soon' item for future expansion
- **View System**: Implemented a view-based architecture for easy navigation between sections
- **Grid Layout**: Modern CSS Grid layout with 220px sidebar and flexible main content
- **Dark Mode Support**: Full dark mode compatibility for the sidebar
- **Responsive Design**: Maintains mobile compatibility while adding desktop navigation
- **Visual Feedback**: Active states, hover effects, and smooth transitions
- **HTML Structure**: Clean …
=> feat: Add left panel navigation with Server Mgmt default

server/api/knowledge.py, server/templates/knowledge_scripts.html
This PR implements server-side relevance ordering for the code viewer search functionality, significantly improving performance and user experience by moving search logic from client-side JavaScript to the backend API.
- **Added `calculate_class_relevance_score()` function** with sophisticated scoring algorithm:
- Exact name match: 1000 points (highest priority)
- Name starts with query: 800 points  
- Name contains query: 600 points
- File path contains query: 400 points
- **Enhanced `api_code_viewer_classes()` endpoint** to accept optional `search` query parameter
- **Bonus scoring factors**: Shorter class names, member count, and ctags source quality
- **Smart result limiting**: Returns top 20 most relevant results for search queries
- **Replaced client-side filtering** with …
=> feat: implement server-side relevance ordering for code viewer search

mcp_tools/kv_store/tool.py
This PR standardizes the code formatting in the KV store tool to improve consistency and readability across the codebase.
- **Quote Consistency**: Converted single quotes to double quotes throughout the file for consistency with project standards
- **Code Formatting**: Improved multiline formatting and parameter alignment for better readability
- **Schema Enhancement**: Enhanced type definitions with proper array types in input schema
- **Dictionary Formatting**: Improved formatting of dictionary returns for better code structure
- **Function Parameters**: Better formatted function parameters with proper line breaks
- All existing functionality is preserved
- No changes to the public API or behavior
- Pre-commit hooks passed successfully
- Code maintains full backward compatibility
- …
=> refactor: standardize code formatting in KV store tool
